#!/bin/bash -l

#SBATCH --partition=uoa-compute
#SBATCH --time=0:30:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=4G
#SBATCH --mail-type=ALL
#SBATCH --mail-user=s05am3@abdn.ac.uk

conda activate /uoa/scratch/shared/Soil_Microbiology_Group/libs/conda/envs/dada2_amplicon
conda info --envs

srun -l seq_to_phyloseq.sh -a -i 01_data/00_input -f _1 -r _2
#srun -l cluster_otus.sh -c 99 
