#!/bin/bash -l

#SBATCH --partition=uoa-compute
#SBATCH --time=0:30:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=4G
#SBATCH --mail-type=ALL
#SBATCH --mail-user=r01db22@abdn.ac.uk

bioconda3
conda activate /uoa/scratch/shared/Soil_Microbiology_Group/usr/conda/envs/microbiome
conda info --envs

#seq_to_phyloseq.sh -a -i 01_data/00_input -f R1 -r R2
#cluster_otus.sh -c 99 
