#!/usr/bin/env Rscript
## Takes a phyloseq object and creates an
## OTU table as would be generated by OTU clustering

library(phyloseq)
library(speedyseq)
library(DECIPHER)
source("./R/write.dataset.R")

args = commandArgs(trailingOnly=TRUE)
# Test if there is at least one argument: if not, default to 99%
if (length(args)==0) {
  stop("Please supply cutoff percentage and input file as arguments.", call.=FALSE)
}

nproc <- 8 # Set to number of cpus/processors to use for the clustering
cluster_cutoff <- (100 - as.numeric(args[1])) / 100 # Cutoff for clustering is (1 - similarity) ie 99% similarity is 0.01 cutoff
ps0 <- readRDS(file = "./02_out/ps.Rds")
# Limit taxonomy table to 6 levels
tax_table(ps0) <- subset(tax_table(ps0), select = -c(8:11))
#Align ASV sequences, calculate distance matrix and create clusters based on required cutoff distance
dna <- refseq(ps0)
aln <- DECIPHER::AlignSeqs(dna, processors = nproc)
d <- DECIPHER::DistanceMatrix(aln, processors = nproc)
clusters <- DECIPHER::IdClusters(d, method = "complete", cutoff = cluster_cutoff, processors = nproc)
## DECIPHER::IdClusters is deprecated, if it fails use DECIPHER::TreeLine
#clusters <- DECIPHER::TreeLine(myDistMatrix=d, method = "complete", cutoff = cluster_cutoff, type = "clusters", processors = nproc)
#Merge input ASVs based on calculated clusters
ps <- merge_taxa_vec(ps0, group = clusters$cluster, tax_adjust = 2)
taxa_names(ps) <- paste0("OTU", seq(ntaxa(ps)))
saveRDS(ps, file = paste0("./02_out/ps_", args[2], "_", args[1], ".Rds"))
write.dataset(ps, filePATH="./02_out/", filePREFIX = paste0("ps_", args[2], "_", args[1]))