#!/usr/bin/env Rscript
## Takes a phyloseq object and creates an
## OTU table as would be generated by OTU clustering

#library(dada2)
#library(Biostrings)
library(phyloseq, lib.loc = "/uoa/scratch/shared/Soil_Microbiology_Group/tools/r_libs/common")
library(speedyseq, lib.loc = "/uoa/scratch/shared/Soil_Microbiology_Group/tools/r_libs/common")
library(DECIPHER, lib.loc = "/uoa/scratch/shared/Soil_Microbiology_Group/tools/r_libs/common")
library(tibble)

args = commandArgs(trailingOnly=TRUE)
# test if there is at least one argument: if not, default to 99%
if (length(args)==0) {
  args[1] = 99
}

nproc <- 4 # set to number of cpus/processors to use for the clustering
cluster_cutoff <- (100 - as.numeric(args[1])) / 100 #Cutoff for clustering is 1 - similarity ie 99% similarity is 0.01 cutoff
ps0 <- readRDS(file = "./02_out/ps.Rds")
tax_table(ps0) <- subset(tax_table(ps0), select = -c(8:11))

dna <- refseq(ps0)
aln <- DECIPHER::AlignSeqs(dna, processors = nproc)
d <- DECIPHER::DistanceMatrix(aln, processors = nproc)
clusters <- DECIPHER::IdClusters(d, method = "complete", cutoff = cluster_cutoff, processors = nproc)
## DECIPHER::IdClusters is deprecated, if it fails use DECIPHER::TreeLine
#clusters <- DECIPHER::TreeLine(myDistMatrix=d, method = "complete", cutoff = cluster_cutoff, type = "clusters", processors = nproc)

ps <- merge_taxa_vec(ps0, group = clusters$cluster, tax_adjust = 2)

taxa_names(ps) <- paste0("OTU", seq(ntaxa(ps)))
saveRDS(ps, file = paste0("./02_out/ps_", args[1], ".Rds"))

OTU1 = t(as(otu_table(ps), "matrix"))
OTUdf = as.data.frame(OTU1)
write.table(OTUdf, file = paste0("./02_out/ps_", args[1], ".otu"), sep = '\t')