## Takes the sequence table generated by DADA2 (seqtab) and clusters OTUs

cluster_asv_dada2 <- function(seqtab,
                              similarity = 99,
                              nproc = 4) {
  asv_sequences <- colnames(seqtab)
  dna <- Biostrings::DNAStringSet(asv_sequences)
  aln <- DECIPHER::AlignSeqs(dna, processors = nproc)
  d <- DECIPHER::DistanceMatrix(aln, processors = nproc)
  clusters <- DECIPHER::TreeLine(
    myDistMatrix = d,
    method = "complete",
    cutoff = 1 - similarity / 100,
    type = "clusters",
    processors = nproc
  )
  clusters <- clusters %>%
    add_column(sequence = asv_sequences)
  seqtab_clustered <- seqtab %>%
    t %>%
    rowsum(clusters$cluster) %>%
    t
  return(seqtab_clustered)
}

## Takes a phyloseq object with sequence data and clusters ASVs to OTUs

cluster_asv_phyloseq <- function(phys,
                                 similarity = 99,
                                 nproc = 4) {
  dna <- refseq(phys)
  aln <- DECIPHER::AlignSeqs(dna, processors = nproc)
  d <- DECIPHER::DistanceMatrix(aln, processors = nproc)
  clusters <- DECIPHER::TreeLine(
    myDistMatrix = d,
    method = "complete",
    cutoff = 1 - similarity / 100,
    type = "clusters",
    processors = nproc
  )
  ps <-
    speedyseq::merge_taxa_vec(phys, group = clusters$cluster, tax_adjust = 2)
  taxa_names(ps) <- paste0("OTU", seq(ntaxa(ps)))
  return(ps)
}