#!/usr/bin/env Rscript
## Takes a phyloseq object and creates an
## OTU table as would be generated by OTU clustering

library(phyloseq)
library(speedyseq)
library(DECIPHER)
source("/uoa/scratch/shared/Soil_Microbiology_Group/libs/R/cluster_asv.R")
source("/uoa/scratch/shared/Soil_Microbiology_Group/libs/R/write_dataset.R")

args = commandArgs(trailingOnly=TRUE)
# Test if there is at least one argument: if not, default to 99%
if (length(args)==0) {
  stop("Please supply cutoff percentage and input file as arguments.", call.=FALSE)
}

nproc <- 8 # Set to number of cpus/processors to use for the clustering
cluster_cutoff <- args[1] # Set the similarity cutoff of clustering
file_base <- tools::file_path_sans_ext(basename(args[2]))

ps0 <- readRDS(file = args[2])
#Align ASV sequences, calculate distance matrix and create clusters based on required cutoff distance
ps <- cluster_asv_phyloseq(ps0, similarity = cluster_cutoff, nproc = nproc)
saveRDS(ps, file = paste0("./02_out/", file_base, "_", args[1], ".Rds"))
write.dataset(ps, filePATH="./02_out/", filePREFIX = paste0(file_base, "_", args[1]))
