#!/usr/bin/env Rscript
## Takes the sequence table generated by DADA2 (seqtab.nochim) and creates an
## OTU table as would be generated by OTU clustering

library(tibble)
library(DECIPHER)
library(Biostrings)

args = commandArgs(trailingOnly=TRUE)
# test if there is at least one argument: if not, default to 99%
if (length(args)==0) {
  args[1] = 99
}

nproc <- 4 # set to number of cpus/processors to use for the clustering
cluster_cutoff <- (100 - args[1]) / 100 # Cutoff is 100 - similarity

readRDS(file = "./02_out/ps.Rds")

asv_sequences <- colnames(seqtab.nochim)
sample_names <- rownames(seqtab.nochim)
dna <- Biostrings::DNAStringSet(asv_sequences)
d <- DECIPHER::DistanceMatrix(aln, processors = nproc)
aln <- DECIPHER::AlignSeqs(dna, processors = nproc)
d <- DECIPHER::DistanceMatrix(aln, processors = nproc)
clusters <- DECIPHER::TreeLine(
  myDistMatrix=d, 
  method = "complete",
  cutoff = cluster_cutoff, 
  type = "clusters",
  processors = nproc)
clusters <- clusters %>%
  add_column(sequence = asv_sequences)
seqtab.clustered <- seqtab.nochim %>% 
  t %>%
  rowsum(clusters$cluster) %>%
  t

taxa <- assignTaxonomy(seqtab.clustered, "/uoa/scratch/shared/Soil_Microbiology_Group/Public_databases/silva_nr99_v138.1_train_set.fa.gz", multithread=TRUE)
taxa <- addSpecies(taxa, "/uoa/scratch/shared/Soil_Microbiology_Group/Public_databases/silva_species_assignment_v138.1.fa.gz")
samples.out <- rownames(seqtab.clustered)
samdf <- read.csv("./00_ref/metadata.csv")
rownames(samdf) <- samples.out
ps <- phyloseq(otu_table(seqtab.clustered, taxa_are_rows=FALSE), sample_data(samdf), tax_table(taxa))
dna <- Biostrings::DNAStringSet(taxa_names(ps))
names(dna) <- taxa_names(ps)
ps <- merge_phyloseq(ps, dna)
taxa_names(ps) <- paste0("OTU", seq(ntaxa(ps)))
saveRDS(ps, file = paste0("./02_out/ps_", args[1], ".Rds"))

OTU1 = t(as(otu_table(ps), "matrix"))
OTUdf = as.data.frame(OTU1)
write.table(OTUdf, file = paste0("./02_out/ps_", args[1], ".otu"), sep = '\t')

